---

- name: Create web server config dir if needed and possible
  file:
    dest: "{{ interactive_environments_web_conf_dir }}"
    state: directory

- name: Create web server config snippet for IE proxy
  template:
    src: "{{ interactive_environments_web_conf_templates[item] }}.j2"
    dest: "{{ interactive_environments_web_conf_dir }}/{{ interactive_environments_web_conf_templates[item] }}"
  with_items: "{{ interactive_environments_enabled }}"
  when: item in interactive_environments_web_conf_templates
